version: "3.1"
services:
  orthanc:
    image: jodogne/orthanc-plugins:latest
    container_name: orthanc-server-prototype
    command: /run/secrets/
    ports:
      - 4242:4242
      - 8042:8042
    secrets:
      - orthanc.json
    volumes:
      - ./orthanc.json:/etc/orthanc/orthanc.json:ro
      - ./orthanc_db:/var/lib/orthanc/db/ # making database persistent
    restart: always
    networks:
      - pacs
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: postgres_orthanc_db
    environment:
      POSTGRES_USER: orthanc
      POSTGRES_PASSWORD: orthanc
      POSTGRES_DB: orthanc
    volumes:
      - postgres_data:/var/lib/postgresql/data

  ohif_viewer:
    container_name: ohif-viewer-prototype
    image: ohif/viewer
    ports:
      - 8080:80
    environment:
      - APP_CONFIG:/usr/share/nginx/html/app-config.js
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./ohif.js:/usr/share/nginx/html/app-config.js:ro
      - ./logo.png:/usr/share/nginx/html/logo.png:ro
    restart: always
    networks:
      - pacs

secrets:
  orthanc.json:
    file: orthanc.json

volumes:
  postgres_data:

networks:
  pacs:
    external: true
