version: "3.1" # Secrets are only available since this version of Docker Compose
services:
  orthanc:
    image: jodogne/orthanc-plugins:1.12.4
    command: /run/secrets/ # Path to the configuration files (stored as secrets)
    ports:
      - 4242:4242
      - 8042:8042
    secrets:
      - orthanc.json
    environment:
      - ORTHANC_NAME=HelloWorld

  pgadmin:
    container_name: pgadmin4-view
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: root@root.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5051:5051"

  db:
    restart: unless-stopped
    image: postgres
    container_name: cont-postgres
    volumes:
      - orthanc_db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB="ORTHANC"
      - POSTGRES_USER="postgres"
      - POSTGRES_PASSWORD="12343"
      - POSTGRES_PORT="5432"
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

secrets:
  orthanc.json:
    file: orthanc.json

volumes:
  orthanc_db_data:
